### ISSUE TITLE
segfault report

### ISSUE THREAD

**Issue by rogelio-telnyx** [sipcapture/heplify-server#127]
I'd like to report issues of heplify-server crashing when running in production.
Here's the interesting part of the logs:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x81770e]
goroutine 482 [running]:
github.com/negbie/heplify-server/database.formDataHeader(0xc42885f5f0, 0xc42731d400, 0x1a, 0x122, 0x1a, 0xc42731d400)
    /go/src/github.com/negbie/heplify-server/database/sqlhomer7.go:374 +0xde
github.com/negbie/heplify-server/database.(*SQLHomer7).insert(0xc421729230, 0xc421794780)
    /go/src/github.com/negbie/heplify-server/database/sqlhomer7.go:125 +0x76c
github.com/negbie/heplify-server/database.(*Database).Run.func1(0xc4217914a0)
    /go/src/github.com/negbie/heplify-server/database/database.go:59 +0x3c
created by github.com/negbie/heplify-server/database.(*Database).Run
    /go/src/github.com/negbie/heplify-server/database/database.go:58 +0x1ff
```
I'm also attaching the full log in case it helps.
[heplify-server.log](https://github.com/sipcapture/heplify-server/files/2395425/heplify-server.log)
Thanks

**Comment by rogelio-telnyx** [comment]
Hello, for the DB we're using the default config file from the postgres:10.5-alpine docker image:

> #max_locks_per_transaction = 64         # min 10  
> shared_buffers = 128MB                  # min 128kB  

Upon starting heplify-server it sends approx 250pps of HEP and the mem usage of the postgres container spikes up to 1GB, until heplify-server crashes.

**Comment by negbie** [comment]
Do you still have the "out of shared memory" warnings?

**Comment by rogelio-telnyx** [comment]
Yes I do, I haven't made any changes yet.

**Comment by negbie** [comment]
@rogelio-telnyx please do following. mount a postgresql.conf file like:

    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
     command: 'postgres -c config_file="/etc/postgresql.conf"'

raise inside postgresql.conf max_locks_per_transaction like:

max_locks_per_transaction = 512
Keep an eye on your memory from nothing comes nothing so need need enough for your load.

Please tell me how many cores you machine has.

**Comment by rogelio-telnyx** [comment]
@negbie Alexandr has helped us fine tune our postgres instances, and it seems like the shared mem issues is gone, but now heplify-server is crashing every 2 min with the following errors:
```
nodeID: 6553600, protoType: 1, version: 2, protocol: 6, length: 347, flow: 10.255.0.1:46677->10.15.11.4:5070
2018/10/16 19:29:14.445200 decoder.go:125: WARN parseStartLine err: received err while parsing start line: parseStartLineRequest err: request line did not split on LWS correctly
"nt/8000\r\na=fmtp:101 0-15\r\na=sendrecv\r\na=maxptime:20\r\n\r\n--sonus-content-delim\r\nContent-Disposition: signal; handling=required\r\nContent-Length:    55\r\nContent-Type: application/isup; version=ansi88; base=ansi88\r\n\r\n\x01\x10`\x10\n\x03\x06\r\x03\a\x03\x10&(\n\a\x03\x13\"% %\x03\"\x05\x05\b\x03\x10\x15pq\x11=\x01\x1c\x033'B\r\n\r\n--sonus-content-delim--\r\n"
nodeID: 6553600, protoType: 1, version: 2, protocol: 6, length: 281, flow: 10.255.0.1:46677->10.15.11.4:5070
2018/10/16 19:29:15.609049 decoder.go:125: WARN parseStartLine err: received err while parsing start line: parseStartLineRequest err: request line did not split on LWS correctly
"ent/8000\r\na=fmtp:101 0-15\r\na=sendrecv\r\na=maxptime:20\r\n\r\n--sonus-content-delim\r\nContent-Disposition: signal; handling=required\r\nContent-Length:    65\r\nContent-Type: application/isup; version=ansi88; base=ansi88\r\n\r\n\x01\x11H\x10\x03\x06\r\x03\a\x03\x10W$R\n\a\x03\x13YtV\x01\a\x03\x10Yt)DQ\b\x03\x10W$bQ=\x01\x18\x03Y$s\x01=\r\n\r\n--sonus-content-delim--\r\n"
nodeID: 6553600, protoType: 1, version: 2, protocol: 6, length: 288, flow: 10.255.0.1:46677->10.15.11.4:5070
2018/10/16 19:29:15.682227 decoder.go:125: WARN parseStartLine err: received err while parsing start line: parseStartLine err: length of s.Val is less than 3. Invalid start line
"\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:18 G729/8000\r\na=rtpmap:101 telephone-event/8000\r\na=fmtp:101 0-15\r\na=sendrecv\r\na=ptime:20\r\n"
nodeID: 6553600, protoType: 1, version: 2, protocol: 6, length: 145, flow: 10.255.0.1:46677->10.15.11.4:5070
2018/10/16 19:29:16.526109 decoder.go:125: WARN parseStartLine err: received err while parsing start line: parseStartLineRequest err: request line did not split on LWS correctly
"MU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:18 G729/8000\r\na=rtpmap:101 telephone-event/8000\r\na=fmtp:101 0-15\r\na=sendrecv\r\na=ptime:20\r\n\r\n--sonus-content-delim\r\nContent-Disposition: signal; handling=required\r\nContent-Length:    68\r\nContent-Type: application/isup; version=ansi88; base=ansi88\r\n\r\n\x01\x10\b\x10\x03\x06\r\x03\a\x03\x1061\x10\n\a\x03\x13\x197\x11\b\x03\x106A\x03\x19\b\x106q\x16Y`\x10 Cell Phone   NY\r\n--sonus-content-delim--\r\n"
nodeID: 6553600, protoType: 1, version: 2, protocol: 6, length: 368, flow: 10.255.0.1:46677->10.15.11.4:5070
2018/10/16 19:29:16.748856 decoder.go:125: WARN parseStartLine err: received err while parsing start line: parseStartLineRequest err: request line did not split on LWS correctly
"/8000\r\na=fmtp:101 0-15\r\na=sendrecv\r\na=maxptime:20\r\n\r\n--sonus-content-delim\r\nContent-Disposition: signal; handling=required\r\nContent-Length:    53\r\nContent-Type: application/isup; version=ansi88; base=ansi88\r\n\r\n\x01\x10H\x10\n\x03\x06\r\x03\a\x03\x10\ta3\n\a\x03\x137ag\b\x03\x10\t!!=\x01\x18\x03\x06!\x01>\r\n\r\n--sonus-content-delim--\r\n"
nodeID: 6553600, protoType: 1, version: 2, protocol: 6, length: 275, flow: 10.255.0.1:46677->10.15.11.4:5070
2018/10/16 19:29:18.057238 decoder.go:125: WARN parseStartLine err: received err while parsing start line: parseStartLineRequest err: request line did not split on LWS correctly
"ent/8000\r\na=fmtp:101 0-15\r\na=sendrecv\r\na=maxptime:20\r\n\r\n--sonus-content-delim\r\nContent-Disposition: signal; handling=required\r\nContent-Length:    50\r\nContent-Type: application/isup; version=ansi88; base=ansi88\r\n\r\n\x01\x10 \x10\n\x03\x06\r\x03\a\x03\x10 \n\a\x03\x133`i\x01R\b\x03\x10\x16d1q@=\x01\x11\x03\x164\x10\r\n\r\n--sonus-content-delim--\r\n"
nodeID: 6553600, protoType: 1, version: 2, protocol: 6, length: 279, flow: 10.255.0.1:46677->10.15.11.4:5070
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x812844]
goroutine 491 [running]:
github.com/negbie/heplify-server/database.(*SQLHomer7).insert(0xc421c94090, 0xc42186c0c0)
	/go/src/github.com/negbie/heplify-server/database/sqlhomer7.go:123 +0x784
github.com/negbie/heplify-server/database.(*Database).Run.func1(0xc421bc60c0)
	/go/src/github.com/negbie/heplify-server/database/database.go:59 +0x3c
created by github.com/negbie/heplify-server/database.(*Database).Run
	/go/src/github.com/negbie/heplify-server/database/database.go:58 +0x1ff

```

**Comment by negbie** [comment]
@rogelio-telnyx ok thats good and thanks to alexandr! Since it crashes on regular time would it be possible to send alexandr a pcap so I can take a look on this tomorrow?

**Comment by negbie** [comment]
I still need to know more about your setup. How many cores does your machine has?

**Comment by negbie** [comment]
@rogelio-telnyx I pushed some changes. Please update and give me an update.

**Comment by rogelio-telnyx** [comment]
@negbie we've deployed the latest version and we haven't had any crashes for the last 3hs, which is very promising. Thanks for the fix, I think we can close this issue.
