### ISSUE TITLE
heplify-server crashes on start

### ISSUE THREAD

**Issue by cerienj** [sipcapture/heplify-server#354]
After a few hours of service, it crashes and wont start again

See: https://github.com/sipcapture/homer7-docker/issues/75

```
2020/04/21 13:04:33.813446 prometheus.go:38: INFO expose metrics without or unbalanced targets
panic: not implemented
	panic: not implemented

goroutine 91 [running]:
github.com/golang/protobuf/proto.(*InternalMessageInfo).Size(...)
	/go/src/github.com/golang/protobuf/proto/deprecated.go:91
github.com/sipcapture/heplify-server/remotelog/logproto.(*PushRequest).XXX_Size(0xc0000b3d00, 0xed3740)
	/go/src/github.com/sipcapture/heplify-server/remotelog/logproto/logproto.pb.go:49 +0x3a
github.com/gogo/protobuf/proto.Marshal(0xed3740, 0xc0000b3d00, 0xc0001908f8, 0xc000812050, 0xc000190930, 0x4153ea, 0x7f1c16846400)
	/go/src/github.com/gogo/protobuf/proto/table_marshal.go:2938 +0x278
github.com/sipcapture/heplify-server/remotelog.encodeBatch(0xc000190e98, 0x4153ea, 0x7f1c16879900, 0x100, 0x7f1c16a38fff, 0xc0001909f0)
	/go/src/github.com/sipcapture/heplify-server/remotelog/loki.go:194 +0x1dc
github.com/sipcapture/heplify-server/remotelog.(*Loki).sendBatch(0xc0007fa030, 0xc000190e98, 0x0, 0x0)
	/go/src/github.com/sipcapture/heplify-server/remotelog/loki.go:173 +0x3d
github.com/sipcapture/heplify-server/remotelog.(*Loki).start.func1(0xc0007fa030, 0xc000190e28)
	/go/src/github.com/sipcapture/heplify-server/remotelog/loki.go:83 +0x3c
panic(0xc53b20, 0xeb6060)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/golang/protobuf/proto.(*InternalMessageInfo).Size(...)
	/go/src/github.com/golang/protobuf/proto/deprecated.go:91
github.com/sipcapture/heplify-server/remotelog/logproto.(*PushRequest).XXX_Size(0xc0000b2680, 0xed3740)
	/go/src/github.com/sipcapture/heplify-server/remotelog/logproto/logproto.pb.go:49 +0x3a
github.com/gogo/protobuf/proto.Marshal(0xed3740, 0xc0000b2680, 0xc000190c30, 0xc000812000, 0xc000190d10, 0x43f283, 0xc000190ec8)
	/go/src/github.com/gogo/protobuf/proto/table_marshal.go:2938 +0x278
github.com/sipcapture/heplify-server/remotelog.encodeBatch(0xc000190e98, 0xc000186960, 0xc000190ef0, 0xc0001869c0, 0xc0006a0688, 0xc0006a0738)
	/go/src/github.com/sipcapture/heplify-server/remotelog/loki.go:194 +0x1dc
github.com/sipcapture/heplify-server/remotelog.(*Loki).sendBatch(0xc0007fa030, 0xc000190e98, 0x0, 0x0)
	/go/src/github.com/sipcapture/heplify-server/remotelog/loki.go:173 +0x3d
github.com/sipcapture/heplify-server/remotelog.(*Loki).start(0xc0007fa030, 0xc00020a8a0)
	/go/src/github.com/sipcapture/heplify-server/remotelog/loki.go:161 +0x1373
github.com/sipcapture/heplify-server/remotelog.(*Remotelog).Run.func1(0xc00016c020)
	/go/src/github.com/sipcapture/heplify-server/remotelog/remotelog.go:36 +0x3c
created by github.com/sipcapture/heplify-server/remotelog.(*Remotelog).Run
	/go/src/github.com/sipcapture/heplify-server/remotelog/remotelog.go:35 +0x78
```

**Comment by negbie** [comment]
Ah I see. One or two days ago I updated the protobuf lib which deprecated some stuff. Let me take a look.

**Comment by negbie** [comment]
Here you go https://github.com/sipcapture/heplify-server/pull/357

Please test and report back. Thanks for the report!

**Comment by cerienj** [comment]
Indeed, it is fixed, many thanks:-)

**Comment by negbie** [comment]
Thanks to you for the report! If you are confident that it's fixed just close this issue.
