### ISSUE TITLE
panic when decoding

### ISSUE THREAD

**Issue by okhowang** [sipcapture/heplify-server#520]
version v1.59.3
```
2023-03-20 11:38:17 2023/03/20 03:38:17.398194 decoder.go:117: WARN malformed packet with length 0 which is neither hep nor protobuf encapsulated
2023-03-20 11:38:17 panic: runtime error: slice bounds out of range [16:8]
2023-03-20 11:38:17 
2023-03-20 11:38:17 goroutine 77 [running]:
2023-03-20 11:38:17 github.com/sipcapture/heplify-server/decoder.(*HEP).parseHEP2(0xc000d58c40, {0xc000a24000, 0x8, 0xffe3})
2023-03-20 11:38:17 	/heplify-server/decoder/hep.go:141 +0x37e
2023-03-20 11:38:17 github.com/sipcapture/heplify-server/decoder.(*HEP).parse(0xc000d58c40, {0xc000a24000, 0x8, 0xffe3})
2023-03-20 11:38:17 	/heplify-server/decoder/decoder.go:109 +0x15b
2023-03-20 11:38:17 github.com/sipcapture/heplify-server/decoder.DecodeHEP({0xc000a24000, 0x8, 0xffe3})
2023-03-20 11:38:17 	/heplify-server/decoder/decoder.go:93 +0x48
2023-03-20 11:38:17 github.com/sipcapture/heplify-server/server.(*HEPInput).worker(0xc000328000)
2023-03-20 11:38:17 	/heplify-server/server/server.go:214 +0x3ba
2023-03-20 11:38:17 created by github.com/sipcapture/heplify-server/server.(*HEPInput).Run
2023-03-20 11:38:17 	/heplify-server/server/server.go:88 +0x5a
```

**Comment by okhowang** [comment]
It seem like happened when `readBytes` do read not enough to pkgsize.
https://github.com/sipcapture/heplify-server/blob/master/server/tcp.go#L99
when `n` < size, the packet put into `inputCh` is malformed
maybe we should use `io.ReadFull` instead of `readBytes`?
